#!/usr/bin/env python3
"""从系统 sans-serif 字体渲染 "Codebot" → 1bpp C 位图 (display/codebot_logo.h).

用法: python3 tools/gen_codebot_logo.py
依赖: pip install pillow
"""

import os
import sys

from PIL import Image, ImageFont

FONT_CANDIDATES = [
    # macOS
    "/System/Library/Fonts/Helvetica.ttc",
    "/System/Library/Fonts/Supplemental/Helvetica.ttc",
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/Hiragino Sans GB.ttc",
    "/Library/Fonts/Arial.ttf",
    # Linux
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
    # Windows
    "C:/Windows/Fonts/arialbd.ttf",
]

STRING = "Codebot"
FONT_SIZE = 60  # ~60pt bold, 让 "Codebot" 占满屏宽约 88%

OUT_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "src", "display", "fonts", "code_bot.h",
)


def find_font() -> str:
    for path in FONT_CANDIDATES:
        if os.path.exists(path):
            return path
    raise SystemExit(
        "找不到系统 sans-serif 字体.\n"
        "Linux: sudo apt install fonts-dejavu\n"
        "候选路径:\n  " + "\n  ".join(FONT_CANDIDATES)
    )


def render_to_bits(font_path: str):
    from PIL import ImageDraw

    font = ImageFont.truetype(font_path, FONT_SIZE)
    # getbbox 测真实渲染尺寸 (含 ascender/descender)
    bbox = font.getbbox(STRING)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    # 1bpp Image 上用 ImageDraw 写字, tobytes() 直接得 packed bits (MSB-first).
    img = Image.new("1", (w, h), 0)
    ImageDraw.Draw(img).text((-bbox[0], -bbox[1]), STRING, fill=1, font=font)
    raw = img.tobytes()
    row_stride = (w + 7) // 8

    bits = []
    for y in range(h):
        row_bytes = [raw[y * row_stride + xb] for xb in range(row_stride)]
        bits.append(row_bytes)
    return w, h, bits


def emit_header(w: int, h: int, bits) -> str:
    # LCD 320x172 居中
    x = (320 - w) // 2
    y = (172 - h) // 2
    col_bytes = (w + 7) // 8
    lines = [
        "/* Auto-generated by tools/gen_codebot_logo.py — do not edit. */",
        "#ifndef CODEBOT_LOGO_HEADER_H",
        "#define CODEBOT_LOGO_HEADER_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define CODEBOT_LOGO_W   {w}",
        f"#define CODEBOT_LOGO_H   {h}",
        f"#define CODEBOT_LOGO_X   ({x})",
        f"#define CODEBOT_LOGO_Y   ({y})",
        "",
        f"static const uint8_t codebot_logo_bits[{h}][{col_bytes}] = {{",
    ]
    for row in bits:
        joined = ", ".join(f"0x{b:02x}" for b in row)
        lines.append(f"    {{{joined}}},")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* CODEBOT_LOGO_HEADER_H */")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    font = find_font()
    w, h, bits = render_to_bits(font)
    cx = (320 - w) // 2
    cy = (172 - h) // 2
    print(f"[gen_codebot_logo] font={font}")
    print(f"[gen_codebot_logo] size={w}x{h}, centered at ({cx},{cy})")
    header = emit_header(w, h, bits)
    with open(OUT_PATH, "w") as f:
        f.write(header)
    print(f"[gen_codebot_logo] wrote {OUT_PATH} ({len(header)} bytes)")


if __name__ == "__main__":
    main()